/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author DEV - Santiago
 */
public class Frm_Pantalla_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Pantalla_Principal
     */
    public Frm_Pantalla_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Jgv_tabla_monitoreo = new javax.swing.JTable();
        lbl_factura = new javax.swing.JLabel();
        lbl_retenciones = new javax.swing.JLabel();
        lbl_NC = new javax.swing.JLabel();
        lbl_NDB = new javax.swing.JLabel();
        lbl_facturaZA = new javax.swing.JLabel();
        lbl_NC_ZA = new javax.swing.JLabel();
        lbl_NDB_ZA = new javax.swing.JLabel();
        lbl_guias = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Jgv_tabla_monitoreo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Empresa", "Fecha / hora", "PR", "RC", "PR", "RC", "PR", "RC", "PR", "RC", "PR", "RC", "PR", "RC", "PR", "RC", "PR", "RC"
            }
        ));
        Jgv_tabla_monitoreo.getTableHeader().setResizingAllowed(false);
        Jgv_tabla_monitoreo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Jgv_tabla_monitoreo);
        Jgv_tabla_monitoreo.getAccessibleContext().setAccessibleDescription("");

        lbl_factura.setBackground(new java.awt.Color(255, 255, 255));
        lbl_factura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_factura.setLabelFor(Jgv_tabla_monitoreo);
        lbl_factura.setText("Facturas");
        lbl_factura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_factura.setOpaque(true);

        lbl_retenciones.setBackground(new java.awt.Color(255, 255, 255));
        lbl_retenciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_retenciones.setLabelFor(Jgv_tabla_monitoreo);
        lbl_retenciones.setText("Retenciones");
        lbl_retenciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_retenciones.setOpaque(true);

        lbl_NC.setBackground(new java.awt.Color(255, 255, 255));
        lbl_NC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NC.setLabelFor(Jgv_tabla_monitoreo);
        lbl_NC.setText("Notas de credito");
        lbl_NC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_NC.setOpaque(true);

        lbl_NDB.setBackground(new java.awt.Color(255, 255, 255));
        lbl_NDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NDB.setLabelFor(Jgv_tabla_monitoreo);
        lbl_NDB.setText("Notas de debito");
        lbl_NDB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_NDB.setOpaque(true);

        lbl_facturaZA.setBackground(new java.awt.Color(255, 255, 255));
        lbl_facturaZA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_facturaZA.setLabelFor(Jgv_tabla_monitoreo);
        lbl_facturaZA.setText("Factura - ZA");
        lbl_facturaZA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_facturaZA.setOpaque(true);

        lbl_NC_ZA.setBackground(new java.awt.Color(255, 255, 255));
        lbl_NC_ZA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NC_ZA.setLabelFor(Jgv_tabla_monitoreo);
        lbl_NC_ZA.setText("Nota Credito ZA");
        lbl_NC_ZA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_NC_ZA.setOpaque(true);

        lbl_NDB_ZA.setBackground(new java.awt.Color(255, 255, 255));
        lbl_NDB_ZA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NDB_ZA.setLabelFor(Jgv_tabla_monitoreo);
        lbl_NDB_ZA.setText("Nota debito - ZA");
        lbl_NDB_ZA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_NDB_ZA.setOpaque(true);

        lbl_guias.setBackground(new java.awt.Color(255, 255, 255));
        lbl_guias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_guias.setLabelFor(Jgv_tabla_monitoreo);
        lbl_guias.setText("Guias");
        lbl_guias.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl_guias.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Leyenda"));

        jLabel2.setText("PR = Procesada");

        jLabel3.setText("RC = Rechazadas");

        jLabel4.setText("Documentos rechazados");

        jLabel5.setBackground(new java.awt.Color(255, 0, 51));
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(255, 102, 0));
        jLabel6.setOpaque(true);

        jLabel7.setText("Documentos que no se han procesado en 4 horas o más");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lbl_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_retenciones, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_NC, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_NDB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_guias, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_facturaZA, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_NC_ZA, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_NDB_ZA, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_factura)
                    .addComponent(lbl_retenciones)
                    .addComponent(lbl_NC)
                    .addComponent(lbl_NDB)
                    .addComponent(lbl_facturaZA)
                    .addComponent(lbl_NC_ZA)
                    .addComponent(lbl_NDB_ZA)
                    .addComponent(lbl_guias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    //Ajuste de tamaño de JTable
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frm_Pantalla_Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jgv_tabla_monitoreo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_NC;
    private javax.swing.JLabel lbl_NC_ZA;
    private javax.swing.JLabel lbl_NDB;
    private javax.swing.JLabel lbl_NDB_ZA;
    private javax.swing.JLabel lbl_factura;
    private javax.swing.JLabel lbl_facturaZA;
    private javax.swing.JLabel lbl_guias;
    private javax.swing.JLabel lbl_retenciones;
    // End of variables declaration//GEN-END:variables
}
